// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgdxrrhahenmpmjbqrdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZHhycmhhaGVubXBtamJxcmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTc3MTMsImV4cCI6MjA3MjgzMzcxM30.iiF5rAJromzPunTDhIetoRIsQQMwAtrNyt7B0vpuk-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});